#!/usr/bin/env python3
"""
AvatarArts Terminal Session Exporter - Poolside Adaptation
Creates durable session handoffs for continuation.
"""

import argparse
import json
import re
import subprocess
from datetime import datetime
from pathlib import Path


def get_git_info():
    result = {"branch": None, "head": None, "status_lines": []}
    try:
        result["branch"] = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True
        ).stdout.strip() or None
    except:
        pass
    
    try:
        result["head"] = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True
        ).stdout.strip() or None
    except:
        pass
    
    try:
        status = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True
        ).stdout.strip()
        result["status_lines"] = [l for l in status.splitlines() if l]
    except:
        pass
    
    return result


def slugify(text):
    text = re.sub(r"[^\w\s-]", "", text.lower())
    return re.sub(r"[\s_-]+", "-", text).strip("-")[:30] or "session"


def build_md_export(focus, depth, project, git):
    ts = datetime.now().isoformat()
    
    changes = "\n".join(f"- `{l}`" for l in git["status_lines"][:20]) or "- No changes detected"
    
    content = f"""---
title: "{focus}"
source: "poolside"
exporter: "AvatarArts Terminal Session Exporter"
exporter_version: "1.0.0"
schema_version: "1.0"
exported_at: "{ts}"
project: "{project}"
cwd: "{str(Path.cwd())}"
git_branch: "{git['branch'] or 'null'}"
git_head: "{git['head'] or 'null'}"
status: "partial"
focus: "{focus}"
---

# Session Export — {focus or 'Coding Session'}

## Executive Snapshot

- Session archived via `/export`
- Poolside environment with symlinked skills
- Continuation-ready handoff created

## Original Goal

{focus or 'Continuation of current work session'}

## Workspace Changes

{changes}

## Continuation Prompt

Review this export and continue work. Use memory queries to check prior decisions.

## Provenance and Privacy

Generated by AvatarArts Terminal Session Exporter. Secrets redacted as [REDACTED] where applicable.
"""
    return content


def build_json_export(focus, project, git):
    ts = datetime.now().isoformat()
    return {
        "schema_version": "1.0",
        "exporter": "AvatarArts Terminal Session Exporter",
        "exporter_version": "1.0.0",
        "exported_at": ts,
        "source": "poolside",
        "title": focus,
        "project": project,
        "cwd": str(Path.cwd()),
        "git": {"branch": git["branch"], "head": git["head"]},
        "status": "partial",
        "focus": focus,
        "original_goal": focus,
        "work_completed": [],
        "decisions": [],
        "workspace_changes": git["status_lines"][:20],
        "commands_and_verification": [],
        "errors_and_diagnostics": [],
        "remaining_work": [],
        "continuation_prompt": "Continue work from this export.",
        "session_narrative": [],
        "provenance": "Generated by AvatarArts Terminal Session Exporter",
        "redactions": []
    }


def main():
    parser = argparse.ArgumentParser(description="Export session for continuation")
    parser.add_argument("--focus", default="")
    parser.add_argument("--format", choices=["md", "json"], default="md")
    parser.add_argument("--depth", choices=["compact", "standard", "deep"], default="standard")
    parser.add_argument("--path", type=Path)
    
    args = parser.parse_args()
    
    out_dir = Path(".agent-exports")
    out_dir.mkdir(exist_ok=True)
    
    slug = slugify(args.focus)
    filename = datetime.now().strftime(f"%Y-%m-%d_%H%M%S-{slug}.{args.format}")
    out_path = args.path or out_dir / filename
    
    if out_path.exists():
        base = out_path.stem
        parent = out_path.parent
        ext = out_path.suffix
        i = 2
        while out_path.exists():
            out_path = parent / f"{base}-{i}{ext}"
            i += 1
    
    focus = args.focus or "coding session"
    project = Path.cwd().name
    git = get_git_info()
    
    if args.format == "md":
        content = build_md_export(focus, args.depth, project, git)
    else:
        content = json.dumps(build_json_export(focus, project, git), indent=2)
    
    out_path.write_text(content)
    print(f"Export written: {out_path} ({out_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()