#!/bin/bash
# Reverses the 2026-08-10 invert-at-root migration.
# Restores: real skill dirs back into ~/.agents/skills, and the 37 symlinks
# (34 live + 3 dangling) back into ~/.agent-skills/skills.
set -euo pipefail
CANON="/Users/steven/.agent-skills/skills"
LEGACY="/Users/steven/.agents/skills"

if [ ! -L "$LEGACY" ]; then echo "ABORT: $LEGACY is not a symlink; migration not in applied state." >&2; exit 1; fi
rm "$LEGACY"
mkdir -p "$LEGACY"

mv "$CANON/audiocraft-audio-generation" "$LEGACY/audiocraft-audio-generation"
ln -s "../../.agents/skills/audiocraft-audio-generation" "$CANON/audiocraft-audio-generation"
mv "$CANON/axolotl" "$LEGACY/axolotl"
ln -s "../../.agents/skills/axolotl" "$CANON/axolotl"
mv "$CANON/blackbox" "$LEGACY/blackbox"
ln -s "../../.agents/skills/blackbox" "$CANON/blackbox"
mv "$CANON/chroma" "$LEGACY/chroma"
ln -s "../../.agents/skills/chroma" "$CANON/chroma"
mv "$CANON/claude-code" "$LEGACY/claude-code"
ln -s "../../.agents/skills/claude-code" "$CANON/claude-code"
mv "$CANON/clip" "$LEGACY/clip"
ln -s "../../.agents/skills/clip" "$CANON/clip"
mv "$CANON/code-review" "$LEGACY/code-review"
ln -s "../../.agents/skills/code-review" "$CANON/code-review"
mv "$CANON/codebase-inspection" "$LEGACY/codebase-inspection"
ln -s "../../.agents/skills/codebase-inspection" "$CANON/codebase-inspection"
mv "$CANON/codex" "$LEGACY/codex"
ln -s "../../.agents/skills/codex" "$CANON/codex"
mv "$CANON/distributed-llm-pretraining-torchtitan" "$LEGACY/distributed-llm-pretraining-torchtitan"
ln -s "../../.agents/skills/distributed-llm-pretraining-torchtitan" "$CANON/distributed-llm-pretraining-torchtitan"
mv "$CANON/dogfood" "$LEGACY/dogfood"
ln -s "../../.agents/skills/dogfood" "$CANON/dogfood"
mv "$CANON/dspy" "$LEGACY/dspy"
ln -s "../../.agents/skills/dspy" "$CANON/dspy"
mv "$CANON/duckduckgo-search" "$LEGACY/duckduckgo-search"
ln -s "../../.agents/skills/duckduckgo-search" "$CANON/duckduckgo-search"
mv "$CANON/evaluating-llms-harness" "$LEGACY/evaluating-llms-harness"
ln -s "../../.agents/skills/evaluating-llms-harness" "$CANON/evaluating-llms-harness"
mv "$CANON/fine-tuning-with-trl" "$LEGACY/fine-tuning-with-trl"
ln -s "../../.agents/skills/fine-tuning-with-trl" "$CANON/fine-tuning-with-trl"
mv "$CANON/gguf-quantization" "$LEGACY/gguf-quantization"
ln -s "../../.agents/skills/gguf-quantization" "$CANON/gguf-quantization"
mv "$CANON/heartmula" "$LEGACY/heartmula"
ln -s "../../.agents/skills/heartmula" "$CANON/heartmula"
mv "$CANON/hermes-agent-spawning" "$LEGACY/hermes-agent-spawning"
ln -s "../../.agents/skills/hermes-agent-spawning" "$CANON/hermes-agent-spawning"
mv "$CANON/instructor" "$LEGACY/instructor"
ln -s "../../.agents/skills/instructor" "$CANON/instructor"
mv "$CANON/llava" "$LEGACY/llava"
ln -s "../../.agents/skills/llava" "$CANON/llava"
mv "$CANON/mcporter" "$LEGACY/mcporter"
ln -s "../../.agents/skills/mcporter" "$CANON/mcporter"
mv "$CANON/ml-paper-writing" "$LEGACY/ml-paper-writing"
ln -s "../../.agents/skills/ml-paper-writing" "$CANON/ml-paper-writing"
mv "$CANON/nano-pdf" "$LEGACY/nano-pdf"
ln -s "../../.agents/skills/nano-pdf" "$CANON/nano-pdf"
mv "$CANON/native-mcp" "$LEGACY/native-mcp"
ln -s "../../.agents/skills/native-mcp" "$CANON/native-mcp"
mv "$CANON/notion" "$LEGACY/notion"
ln -s "../../.agents/skills/notion" "$CANON/notion"
mv "$CANON/obsidian" "$LEGACY/obsidian"
ln -s "../../.agents/skills/obsidian" "$CANON/obsidian"
mv "$CANON/ocr-and-documents" "$LEGACY/ocr-and-documents"
ln -s "../../.agents/skills/ocr-and-documents" "$CANON/ocr-and-documents"
mv "$CANON/requesting-code-review" "$LEGACY/requesting-code-review"
ln -s "../../.agents/skills/requesting-code-review" "$CANON/requesting-code-review"
mv "$CANON/songsee" "$LEGACY/songsee"
ln -s "../../.agents/skills/songsee" "$CANON/songsee"
mv "$CANON/stable-diffusion-image-generation" "$LEGACY/stable-diffusion-image-generation"
ln -s "../../.agents/skills/stable-diffusion-image-generation" "$CANON/stable-diffusion-image-generation"
mv "$CANON/subagent-driven-development" "$LEGACY/subagent-driven-development"
ln -s "../../.agents/skills/subagent-driven-development" "$CANON/subagent-driven-development"
mv "$CANON/test-driven-development" "$LEGACY/test-driven-development"
ln -s "../../.agents/skills/test-driven-development" "$CANON/test-driven-development"
mv "$CANON/whisper" "$LEGACY/whisper"
ln -s "../../.agents/skills/whisper" "$CANON/whisper"
mv "$CANON/writing-plans" "$LEGACY/writing-plans"
ln -s "../../.agents/skills/writing-plans" "$CANON/writing-plans"

# recreate the 3 links that were dangling before the migration
ln -s "../../.agents/skills/ai-video-generation" "$CANON/ai-video-generation"
ln -s "../../.agents/skills/ccxt-cli" "$CANON/ccxt-cli"
ln -s "../../.agents/skills/ccxt-python" "$CANON/ccxt-python"

echo "Restored. $LEGACY is a real directory again."
